"""
GTASA Vanilla Vehicle Data, Color Palette, and Tuning Mappings
"""

# Standard 212 GTA San Andreas Vehicles (ID 400 to 611)
VANILLA_VEHICLES = {
    400: {"model": "landstal", "name": "Landstalker", "type": "car", "handling": "LANDSTAL", "shop": "transfender"},
    401: {"model": "bravura", "name": "Bravura", "type": "car", "handling": "BRAVURA", "shop": "transfender"},
    402: {"model": "buffalo", "name": "Buffalo", "type": "car", "handling": "BUFFALO", "shop": "transfender"},
    403: {"model": "linerun", "name": "Linerunner", "type": "car", "handling": "LINERUN", "shop": "none"},
    404: {"model": "peren", "name": "Perennial", "type": "car", "handling": "PEREN", "shop": "transfender"},
    405: {"model": "sentinel", "name": "Sentinel", "type": "car", "handling": "SENTINEL", "shop": "transfender"},
    406: {"model": "dumper", "name": "Dumper", "type": "car", "handling": "DUMPER", "shop": "none"},
    407: {"model": "firetruk", "name": "Fire Truck", "type": "car", "handling": "FIRETRUK", "shop": "none"},
    408: {"model": "trash", "name": "Trashmaster", "type": "car", "handling": "TRASH", "shop": "none"},
    409: {"model": "stretch", "name": "Stretch (Limousine)", "type": "car", "handling": "STRETCH", "shop": "transfender"},
    410: {"model": "manana", "name": "Manana", "type": "car", "handling": "MANANA", "shop": "transfender"},
    411: {"model": "infernus", "name": "Infernus", "type": "car", "handling": "INFERNUS", "shop": "transfender"},
    412: {"model": "voodoo", "name": "Voodoo", "type": "car", "handling": "VOODOO", "shop": "locolowco"},
    413: {"model": "pony", "name": "Pony", "type": "car", "handling": "PONY", "shop": "none"},
    414: {"model": "mule", "name": "Mule", "type": "car", "handling": "MULE", "shop": "none"},
    415: {"model": "cheetah", "name": "Cheetah", "type": "car", "handling": "CHEETAH", "shop": "transfender"},
    416: {"model": "ambulan", "name": "Ambulance", "type": "car", "handling": "AMBULAN", "shop": "none"},
    417: {"model": "leviathn", "name": "Leviathan", "type": "heli", "handling": "LEVIATHN", "shop": "none"},
    418: {"model": "moonbeam", "name": "Moonbeam", "type": "car", "handling": "MOONBEAM", "shop": "transfender"},
    419: {"model": "esperant", "name": "Esperanto", "type": "car", "handling": "ESPERANT", "shop": "transfender"},
    420: {"model": "taxi", "name": "Taxi", "type": "car", "handling": "TAXI", "shop": "transfender"},
    421: {"model": "washing", "name": "Washington", "type": "car", "handling": "WASHING", "shop": "transfender"},
    422: {"model": "bobcat", "name": "Bobcat", "type": "car", "handling": "BOBCAT", "shop": "transfender"},
    423: {"model": "mrwhoop", "name": "Mr. Whoopee", "type": "car", "handling": "MRWHOOP", "shop": "none"},
    424: {"model": "bfinject", "name": "BF Injection", "type": "car", "handling": "BFINJECT", "shop": "transfender"},
    425: {"model": "hunter", "name": "Hunter", "type": "heli", "handling": "HUNTER", "shop": "none"},
    426: {"model": "premier", "name": "Premier", "type": "car", "handling": "PREMIER", "shop": "transfender"},
    427: {"model": "enforcer", "name": "Enforcer", "type": "car", "handling": "ENFORCER", "shop": "none"},
    428: {"model": "securica", "name": "Securicar", "type": "car", "handling": "SECURICA", "shop": "none"},
    429: {"model": "banshee", "name": "Banshee", "type": "car", "handling": "BANSHEE", "shop": "transfender"},
    430: {"model": "predator", "name": "Predator", "type": "boat", "handling": "PREDATOR", "shop": "none"},
    431: {"model": "bus", "name": "Bus", "type": "car", "handling": "BUS", "shop": "none"},
    432: {"model": "rhino", "name": "Rhino (Tank)", "type": "car", "handling": "RHINO", "shop": "none"},
    433: {"model": "barracks", "name": "Barracks", "type": "car", "handling": "BARRACKS", "shop": "none"},
    434: {"model": "hotknife", "name": "Hotknife", "type": "car", "handling": "HOTKNIFE", "shop": "none"},
    435: {"model": "artict1", "name": "Article Trailer 1", "type": "trailer", "handling": "ARTICT1", "shop": "none"},
    436: {"model": "previon", "name": "Previon", "type": "car", "handling": "PREVION", "shop": "transfender"},
    437: {"model": "coach", "name": "Coach", "type": "car", "handling": "COACH", "shop": "none"},
    438: {"model": "cabbie", "name": "Cabbie", "type": "car", "handling": "CABBIE", "shop": "transfender"},
    439: {"model": "stallion", "name": "Stallion", "type": "car", "handling": "STALLION", "shop": "transfender"},
    440: {"model": "rumpo", "name": "Rumpo", "type": "car", "handling": "RUMPO", "shop": "none"},
    441: {"model": "rcbandit", "name": "RC Bandit", "type": "car", "handling": "RCBANDIT", "shop": "none"},
    442: {"model": "romero", "name": "Romero (Hearse)", "type": "car", "handling": "ROMERO", "shop": "transfender"},
    443: {"model": "packer", "name": "Packer", "type": "car", "handling": "PACKER", "shop": "none"},
    444: {"model": "monster", "name": "Monster Truck", "type": "car", "handling": "MONSTER", "shop": "none"},
    445: {"model": "admiral", "name": "Admiral", "type": "car", "handling": "ADMIRAL", "shop": "transfender"},
    446: {"model": "squalo", "name": "Squalo", "type": "boat", "handling": "SQUALO", "shop": "none"},
    447: {"model": "seaspar", "name": "Sea Sparrow", "type": "heli", "handling": "SEASPAR", "shop": "none"},
    448: {"model": "pizzaboy", "name": "Pizza Boy", "type": "bike", "handling": "PIZZABOY", "shop": "none"},
    449: {"model": "tram", "name": "Tram", "type": "car", "handling": "TRAM", "shop": "none"},
    450: {"model": "artict2", "name": "Article Trailer 2", "type": "trailer", "handling": "ARTICT2", "shop": "none"},
    451: {"model": "turismo", "name": "Turismo", "type": "car", "handling": "TURISMO", "shop": "transfender"},
    452: {"model": "speeder", "name": "Speeder", "type": "boat", "handling": "SPEEDER", "shop": "none"},
    453: {"model": "reefer", "name": "Reefer", "type": "boat", "handling": "REEFER", "shop": "none"},
    454: {"model": "tropic", "name": "Tropic", "type": "boat", "handling": "TROPIC", "shop": "none"},
    455: {"model": "flatbed", "name": "Flatbed", "type": "car", "handling": "FLATBED", "shop": "none"},
    456: {"model": "yankee", "name": "Yankee", "type": "car", "handling": "YANKEE", "shop": "none"},
    457: {"model": "caddy", "name": "Caddy (Golf)", "type": "car", "handling": "CADDY", "shop": "none"},
    458: {"model": "solair", "name": "Solair", "type": "car", "handling": "SOLAIR", "shop": "transfender"},
    459: {"model": "topfun", "name": "Berkley's RC Van", "type": "car", "handling": "TOPFUN", "shop": "none"},
    460: {"model": "skimmer", "name": "Skimmer (Seaplane)", "type": "plane", "handling": "SKIMMER", "shop": "none"},
    461: {"model": "pcj600", "name": "PCJ-600", "type": "bike", "handling": "PCJ600", "shop": "none"},
    462: {"model": "faggio", "name": "Faggio", "type": "bike", "handling": "FAGGIO", "shop": "none"},
    463: {"model": "freeway", "name": "Freeway", "type": "bike", "handling": "FREEWAY", "shop": "none"},
    464: {"model": "rcbaron", "name": "RC Baron", "type": "plane", "handling": "RCBARON", "shop": "none"},
    465: {"model": "rcraider", "name": "RC Raider", "type": "heli", "handling": "RCRAIDER", "shop": "none"},
    466: {"model": "glendale", "name": "Glendale", "type": "car", "handling": "GLENDALE", "shop": "transfender"},
    467: {"model": "oceanic", "name": "Oceanic", "type": "car", "handling": "OCEANIC", "shop": "transfender"},
    468: {"model": "sanchez", "name": "Sanchez", "type": "bike", "handling": "SANCHEZ", "shop": "none"},
    469: {"model": "sparrow", "name": "Sparrow", "type": "heli", "handling": "SPARROW", "shop": "none"},
    470: {"model": "patriot", "name": "Patriot", "type": "car", "handling": "PATRIOT", "shop": "none"},
    471: {"model": "quad", "name": "Quad", "type": "bike", "handling": "QUAD", "shop": "none"},
    472: {"model": "coastg", "name": "Coastguard", "type": "boat", "handling": "COASTG", "shop": "none"},
    473: {"model": "dinghy", "name": "Dinghy", "type": "boat", "handling": "DINGHY", "shop": "none"},
    474: {"model": "hermes", "name": "Hermes", "type": "car", "handling": "HERMES", "shop": "transfender"},
    475: {"model": "sabre", "name": "Sabre", "type": "car", "handling": "SABRE", "shop": "transfender"},
    476: {"model": "rustler", "name": "Rustler", "type": "plane", "handling": "RUSTLER", "shop": "none"},
    477: {"model": "zr350", "name": "ZR-350", "type": "car", "handling": "ZR350", "shop": "transfender"},
    478: {"model": "walton", "name": "Walton", "type": "car", "handling": "WALTON", "shop": "transfender"},
    479: {"model": "regina", "name": "Regina", "type": "car", "handling": "REGINA", "shop": "transfender"},
    480: {"model": "comet", "name": "Comet", "type": "car", "handling": "COMET", "shop": "transfender"},
    481: {"model": "bmx", "name": "BMX", "type": "bike", "handling": "BMX", "shop": "none"},
    482: {"model": "burrito", "name": "Burrito", "type": "car", "handling": "BURRITO", "shop": "none"},
    483: {"model": "camper", "name": "Camper", "type": "car", "handling": "CAMPER", "shop": "none"},
    484: {"model": "marquis", "name": "Marquis", "type": "boat", "handling": "MARQUIS", "shop": "none"},
    485: {"model": "baggage", "name": "Baggage", "type": "car", "handling": "BAGGAGE", "shop": "none"},
    486: {"model": "dozer", "name": "Dozer", "type": "car", "handling": "DOZER", "shop": "none"},
    487: {"model": "maverick", "name": "Maverick", "type": "heli", "handling": "MAVERICK", "shop": "none"},
    488: {"model": "sanmav", "name": "News Maverick", "type": "heli", "handling": "SANMAV", "shop": "none"},
    489: {"model": "rancher", "name": "Rancher", "type": "car", "handling": "RANCHER", "shop": "none"},
    490: {"model": "fbiranch", "name": "FBI Rancher", "type": "car", "handling": "FBIRANCH", "shop": "none"},
    491: {"model": "virgo", "name": "Virgo", "type": "car", "handling": "VIRGO", "shop": "transfender"},
    492: {"model": "greenwoo", "name": "Greenwood", "type": "car", "handling": "GREENWOO", "shop": "transfender"},
    493: {"model": "jetmax", "name": "Jetmax", "type": "boat", "handling": "JETMAX", "shop": "none"},
    494: {"model": "hotring", "name": "Hotring Racer 1", "type": "car", "handling": "HOTRING", "shop": "none"},
    495: {"model": "sandking", "name": "Sandking", "type": "car", "handling": "SANDKING", "shop": "none"},
    496: {"model": "blistac", "name": "Blista Compact", "type": "car", "handling": "BLISTAC", "shop": "transfender"},
    497: {"model": "polmav", "name": "Police Maverick", "type": "heli", "handling": "POLMAV", "shop": "none"},
    498: {"model": "boxville", "name": "Boxville", "type": "car", "handling": "BOXVILLE", "shop": "none"},
    499: {"model": "benson", "name": "Benson", "type": "car", "handling": "BENSON", "shop": "none"},
    500: {"model": "mesa", "name": "Mesa", "type": "car", "handling": "MESA", "shop": "transfender"},
    501: {"model": "rcgoblin", "name": "RC Goblin", "type": "heli", "handling": "RCGOBLIN", "shop": "none"},
    502: {"model": "hotrina", "name": "Hotring Racer 2", "type": "car", "handling": "HOTRINA", "shop": "none"},
    503: {"model": "hotrinb", "name": "Hotring Racer 3", "type": "car", "handling": "HOTRINB", "shop": "none"},
    504: {"model": "bloodra", "name": "Bloodring Banger", "type": "car", "handling": "BLOODRA", "shop": "none"},
    505: {"model": "rnchlure", "name": "Rancher (Lure)", "type": "car", "handling": "RNCHLURE", "shop": "none"},
    506: {"model": "supergt", "name": "Super GT", "type": "car", "handling": "SUPERGT", "shop": "transfender"},
    507: {"model": "elegant", "name": "Elegant", "type": "car", "handling": "ELEGANT", "shop": "transfender"},
    508: {"model": "journey", "name": "Journey", "type": "car", "handling": "JOURNEY", "shop": "none"},
    509: {"model": "bike", "name": "Bike", "type": "bike", "handling": "BIKE", "shop": "none"},
    510: {"model": "mtbike", "name": "Mountain Bike", "type": "bike", "handling": "MTBIKE", "shop": "none"},
    511: {"model": "beagle", "name": "Beagle", "type": "plane", "handling": "BEAGLE", "shop": "none"},
    512: {"model": "cropdust", "name": "Cropduster", "type": "plane", "handling": "CROPDUST", "shop": "none"},
    513: {"model": "stunt", "name": "Stuntplane", "type": "plane", "handling": "STUNT", "shop": "none"},
    514: {"model": "petro", "name": "Petro Tanker", "type": "car", "handling": "PETRO", "shop": "none"},
    515: {"model": "rdtrain", "name": "Roadtrain", "type": "car", "handling": "RDTRAIN", "shop": "none"},
    516: {"model": "nebula", "name": "Nebula", "type": "car", "handling": "NEBULA", "shop": "transfender"},
    517: {"model": "majestic", "name": "Majestic", "type": "car", "handling": "MAJESTIC", "shop": "transfender"},
    518: {"model": "buccanee", "name": "Buccaneer", "type": "car", "handling": "BUCCANEE", "shop": "transfender"},
    519: {"model": "shamal", "name": "Shamal", "type": "plane", "handling": "SHAMAL", "shop": "none"},
    520: {"model": "hydra", "name": "Hydra (Fighter Jet)", "type": "plane", "handling": "HYDRA", "shop": "none"},
    521: {"model": "fcr900", "name": "FCR-900", "type": "bike", "handling": "FCR900", "shop": "none"},
    522: {"model": "nrg500", "name": "NRG-500", "type": "bike", "handling": "NRG500", "shop": "none"},
    523: {"model": "copbike", "name": "HPV-1000 (Police Bike)", "type": "bike", "handling": "COPBIKE", "shop": "none"},
    524: {"model": "cement", "name": "Cement Truck", "type": "car", "handling": "CEMENT", "shop": "none"},
    525: {"model": "towtruck", "name": "Towtruck", "type": "car", "handling": "TOWTRUCK", "shop": "none"},
    526: {"model": "fortune", "name": "Fortune", "type": "car", "handling": "FORTUNE", "shop": "transfender"},
    527: {"model": "cadrona", "name": "Cadrona", "type": "car", "handling": "CADRONA", "shop": "transfender"},
    528: {"model": "fbitruck", "name": "FBI Truck", "type": "car", "handling": "FBITRUCK", "shop": "none"},
    529: {"model": "willard", "name": "Willard", "type": "car", "handling": "WILLARD", "shop": "transfender"},
    530: {"model": "forklift", "name": "Forklift", "type": "car", "handling": "FORKLIFT", "shop": "none"},
    531: {"model": "tractor", "name": "Tractor", "type": "car", "handling": "TRACTOR", "shop": "none"},
    532: {"model": "combine", "name": "Combine Harvester", "type": "car", "handling": "COMBINE", "shop": "none"},
    533: {"model": "feltzer", "name": "Feltzer", "type": "car", "handling": "FELTZER", "shop": "transfender"},
    534: {"model": "remingtn", "name": "Remington", "type": "car", "handling": "REMINGTN", "shop": "locolowco"},
    535: {"model": "slamvan", "name": "Slamvan", "type": "car", "handling": "SLAMVAN", "shop": "locolowco"},
    536: {"model": "blade", "name": "Blade", "type": "car", "handling": "BLADE", "shop": "locolowco"},
    537: {"model": "freight", "name": "Freight", "type": "car", "handling": "FREIGHT", "shop": "none"},
    538: {"model": "streak", "name": "Brown Streak", "type": "car", "handling": "STREAK", "shop": "none"},
    539: {"model": "vortex", "name": "Vortex (Hovercraft)", "type": "boat", "handling": "VORTEX", "shop": "none"},
    540: {"model": "vincent", "name": "Vincent", "type": "car", "handling": "VINCENT", "shop": "transfender"},
    541: {"model": "bullet", "name": "Bullet", "type": "car", "handling": "BULLET", "shop": "transfender"},
    542: {"model": "clover", "name": "Clover", "type": "car", "handling": "CLOVER", "shop": "transfender"},
    543: {"model": "sadler", "name": "Sadler", "type": "car", "handling": "SADLER", "shop": "none"},
    544: {"model": "firela", "name": "Fire Truck (Ladder)", "type": "car", "handling": "FIRELA", "shop": "none"},
    545: {"model": "hustler", "name": "Hustler", "type": "car", "handling": "HUSTLER", "shop": "transfender"},
    546: {"model": "intruder", "name": "Intruder", "type": "car", "handling": "INTRUDER", "shop": "transfender"},
    547: {"model": "primo", "name": "Primo", "type": "car", "handling": "PRIMO", "shop": "transfender"},
    548: {"model": "cargobob", "name": "Cargobob", "type": "heli", "handling": "CARGOBOB", "shop": "none"},
    549: {"model": "tampa", "name": "Tampa", "type": "car", "handling": "TAMPA", "shop": "transfender"},
    550: {"model": "sunrise", "name": "Sunrise", "type": "car", "handling": "SUNRISE", "shop": "transfender"},
    551: {"model": "merit", "name": "Merit", "type": "car", "handling": "MERIT", "shop": "transfender"},
    552: {"model": "utility", "name": "Utility Van", "type": "car", "handling": "UTILITY", "shop": "none"},
    553: {"model": "nevada", "name": "Nevada", "type": "plane", "handling": "NEVADA", "shop": "none"},
    554: {"model": "yosemite", "name": "Yosemite", "type": "car", "handling": "YOSEMITE", "shop": "none"},
    555: {"model": "windsor", "name": "Windsor", "type": "car", "handling": "WINDSOR", "shop": "transfender"},
    556: {"model": "monstera", "name": "Monster Truck A", "type": "car", "handling": "MONSTERA", "shop": "none"},
    557: {"model": "monsterb", "name": "Monster Truck B", "type": "car", "handling": "MONSTERB", "shop": "none"},
    558: {"model": "uranus", "name": "Uranus", "type": "car", "handling": "URANUS", "shop": "wheelarchangels"},
    559: {"model": "jester", "name": "Jester", "type": "car", "handling": "JESTER", "shop": "wheelarchangels"},
    560: {"model": "sultan", "name": "Sultan", "type": "car", "handling": "SULTAN", "shop": "wheelarchangels"},
    561: {"model": "stratum", "name": "Stratum", "type": "car", "handling": "STRATUM", "shop": "wheelarchangels"},
    562: {"model": "elegy", "name": "Elegy", "type": "car", "handling": "ELEGY", "shop": "wheelarchangels"},
    563: {"model": "raindanc", "name": "Raindance", "type": "heli", "handling": "RAINDANC", "shop": "none"},
    564: {"model": "rctiger", "name": "RC Tiger", "type": "car", "handling": "RCTIGER", "shop": "none"},
    565: {"model": "flash", "name": "Flash", "type": "car", "handling": "FLASH", "shop": "wheelarchangels"},
    566: {"model": "tahoma", "name": "Tahoma", "type": "car", "handling": "TAHOMA", "shop": "locolowco"},
    567: {"model": "savanna", "name": "Savanna", "type": "car", "handling": "SAVANNA", "shop": "locolowco"},
    568: {"model": "bandito", "name": "Bandito", "type": "car", "handling": "BANDITO", "shop": "none"},
    569: {"model": "freiflat", "name": "Freight Flat Trailer", "type": "trailer", "handling": "FREIFLAT", "shop": "none"},
    570: {"model": "streakc", "name": "Streak Carriage", "type": "car", "handling": "STREAKC", "shop": "none"},
    571: {"model": "kart", "name": "Kart", "type": "car", "handling": "KART", "shop": "none"},
    572: {"model": "mower", "name": "Mower", "type": "car", "handling": "MOWER", "shop": "none"},
    573: {"model": "duneride", "name": "Dune", "type": "car", "handling": "DUNERIDE", "shop": "none"},
    574: {"model": "sweeper", "name": "Sweeper", "type": "car", "handling": "SWEEPER", "shop": "none"},
    575: {"model": "broadway", "name": "Broadway", "type": "car", "handling": "BROADWAY", "shop": "locolowco"},
    576: {"model": "tornado", "name": "Tornado", "type": "car", "handling": "TORNADO", "shop": "locolowco"},
    577: {"model": "at400", "name": "AT-400", "type": "plane", "handling": "AT400", "shop": "none"},
    578: {"model": "dft30", "name": "DFT-30", "type": "car", "handling": "DFT30", "shop": "none"},
    579: {"model": "huntley", "name": "Huntley", "type": "car", "handling": "HUNTLEY", "shop": "transfender"},
    580: {"model": "stafford", "name": "Stafford", "type": "car", "handling": "STAFFORD", "shop": "transfender"},
    581: {"model": "bf400", "name": "BF-400", "type": "bike", "handling": "BF400", "shop": "none"},
    582: {"model": "newsvan", "name": "News Van", "type": "car", "handling": "NEWSVAN", "shop": "none"},
    583: {"model": "tug", "name": "Tug", "type": "car", "handling": "TUG", "shop": "none"},
    584: {"model": "petrotr", "name": "Petro Trailer", "type": "trailer", "handling": "PETROTR", "shop": "none"},
    585: {"model": "emperor", "name": "Emperor", "type": "car", "handling": "EMPEROR", "shop": "transfender"},
    586: {"model": "wayfarer", "name": "Wayfarer", "type": "bike", "handling": "WAYFARER", "shop": "none"},
    587: {"model": "euros", "name": "Euros", "type": "car", "handling": "EUROS", "shop": "transfender"},
    588: {"model": "hotdog", "name": "Hotdog", "type": "car", "handling": "HOTDOG", "shop": "none"},
    589: {"model": "club", "name": "Club", "type": "car", "handling": "CLUB", "shop": "transfender"},
    590: {"model": "freibox", "name": "Freight Box Trailer", "type": "trailer", "handling": "FREIBOX", "shop": "none"},
    591: {"model": "artict3", "name": "Article Trailer 3", "type": "trailer", "handling": "ARTICT3", "shop": "none"},
    592: {"model": "androm", "name": "Andromada", "type": "plane", "handling": "ANDROM", "shop": "none"},
    593: {"model": "dodo", "name": "Dodo", "type": "plane", "handling": "DODO", "shop": "none"},
    594: {"model": "rccam", "name": "RC Cam", "type": "car", "handling": "RCCAM", "shop": "none"},
    595: {"model": "launch", "name": "Launch", "type": "boat", "handling": "LAUNCH", "shop": "none"},
    596: {"model": "copcarla", "name": "Police Car (LSPD)", "type": "car", "handling": "COPCARLA", "shop": "none"},
    597: {"model": "copcarsf", "name": "Police Car (SFPD)", "type": "car", "handling": "COPCARSF", "shop": "none"},
    598: {"model": "copcarvg", "name": "Police Car (LVPD)", "type": "car", "handling": "COPCARVG", "shop": "none"},
    599: {"model": "copcarru", "name": "Police Ranger", "type": "car", "handling": "COPCARRU", "shop": "none"},
    600: {"model": "picador", "name": "Picador", "type": "car", "handling": "PICADOR", "shop": "transfender"},
    601: {"model": "swatvan", "name": "S.W.A.T. Van", "type": "car", "handling": "SWATVAN", "shop": "none"},
    602: {"model": "alpha", "name": "Alpha", "type": "car", "handling": "ALPHA", "shop": "transfender"},
    603: {"model": "phoenix", "name": "Phoenix", "type": "car", "handling": "PHOENIX", "shop": "transfender"},
    604: {"model": "glenshit", "name": "Glendale (Damaged)", "type": "car", "handling": "GLENSHIT", "shop": "none"},
    605: {"model": "sadlshit", "name": "Sadler (Damaged)", "type": "car", "handling": "SADLSHIT", "shop": "none"},
    606: {"model": "bagboxa", "name": "Baggage Trailer A", "type": "trailer", "handling": "BAGBOXA", "shop": "none"},
    607: {"model": "bagboxb", "name": "Baggage Trailer B", "type": "trailer", "handling": "BAGBOXB", "shop": "none"},
    608: {"model": "tugstair", "name": "Tug Stairs Trailer", "type": "trailer", "handling": "TUGSTAIR", "shop": "none"},
    609: {"model": "boxburg", "name": "Boxville (Black/Burglar)", "type": "car", "handling": "BOXBURG", "shop": "none"},
    610: {"model": "farmtr1", "name": "Farm Trailer", "type": "trailer", "handling": "FARMTR1", "shop": "none"},
    611: {"model": "utiltr1", "name": "Utility Trailer", "type": "trailer", "handling": "UTILTR1", "shop": "none"},
}

MODEL_TO_ID = {v["model"].lower(): k for k, v in VANILLA_VEHICLES.items()}

# Common Tuning Part Prefixes and localized descriptions
TUNING_PREFIX_INFO = {
    "spl_": {"category": "spoiler", "name_cn": "Spoiler", "name_en": "Spoiler", "default_price": 500},
    "fbmp_": {"category": "front_bumper", "name_cn": "Front Bumper", "name_en": "Front Bumper", "default_price": 1200},
    "rbmp_": {"category": "rear_bumper", "name_cn": "Rear Bumper", "name_en": "Rear Bumper", "default_price": 1100},
    "exh_": {"category": "exhaust", "name_cn": "Exhaust", "name_en": "Exhaust", "default_price": 350},
    "wg_l_": {"category": "side_skirt_left", "name_cn": "Left Side Skirt", "name_en": "Left Side Skirt", "default_price": 400},
    "wg_r_": {"category": "side_skirt_right", "name_cn": "Right Side Skirt", "name_en": "Right Side Skirt", "default_price": 400},
    "bnt_": {"category": "bonnet", "name_cn": "Bonnet / Hood", "name_en": "Bonnet / Hood", "default_price": 300},
    "bntl_": {"category": "bonnet_vent_l", "name_cn": "Left Bonnet Vent", "name_en": "Left Bonnet Vent", "default_price": 150},
    "bntr_": {"category": "bonnet_vent_r", "name_cn": "Right Bonnet Vent", "name_en": "Right Bonnet Vent", "default_price": 150},
    "rf_": {"category": "roof", "name_cn": "Roof Scoop / Vent", "name_en": "Roof Scoop / Vent", "default_price": 200},
    "lgt_": {"category": "lights", "name_cn": "Lights / Headlights", "name_en": "Lights / Headlights", "default_price": 150},
    "nto_": {"category": "nitro", "name_cn": "Nitro", "name_en": "Nitro", "default_price": 500},
    "fbb_": {"category": "front_bullbar", "name_cn": "Front Bullbar", "name_en": "Front Bullbar", "default_price": 600},
    "bbb_": {"category": "rear_bullbar", "name_cn": "Rear Bullbar", "name_en": "Rear Bullbar", "default_price": 550},
    "misc_": {"category": "misc", "name_cn": "Miscellaneous", "name_en": "Miscellaneous", "default_price": 250},
}

# FLA Special Feature Targets
SPECIAL_FEATURE_TARGETS = {
    "zr350": {
        "label": "zr350",
        "label_en": "zr350",
        "desc": "Flip pop-up headlights that raise when headlights turn on and smoothly retract when off.",
        "desc_en": "Flip pop-up headlights that raise when headlights turn on and smoothly retract when off."
    },
    "sandking": {
        "label": "sandking",
        "label_en": "sandking",
        "desc": "Long-travel monster truck suspension with exceptionally high ground clearance.",
        "desc_en": "Long-travel monster truck suspension with exceptionally high ground clearance."
    },
    "hydra": {
        "label": "hydra",
        "label_en": "hydra",
        "desc": "Jet fighter thrust vectoring and vertical takeoff / hovering.",
        "desc_en": "Jet fighter thrust vectoring and vertical takeoff / hovering."
    },
    "copcarla": {
        "label": "copcarla",
        "label_en": "copcarla",
        "desc": "Dual-color rotating lightbar and siren mechanics.",
        "desc_en": "Dual-color rotating lightbar and siren mechanics."
    },
    "copcarsf": {
        "label": "copcarsf",
        "label_en": "copcarsf",
        "desc": "San Fierro police lightbar and siren mechanics.",
        "desc_en": "San Fierro police lightbar and siren mechanics."
    },
    "copcarvg": {
        "label": "copcarvg",
        "label_en": "copcarvg",
        "desc": "Las Venturas police lightbar and siren mechanics.",
        "desc_en": "Las Venturas police lightbar and siren mechanics."
    },
    "fbiranch": {
        "label": "fbiranch",
        "label_en": "fbiranch",
        "desc": "Dashboard strobe flasher and concealed undercover siren.",
        "desc_en": "Dashboard strobe flasher and concealed undercover siren."
    },
    "taxi": {
        "label": "taxi",
        "label_en": "taxi",
        "desc": "Taxi roof beacon indicator and passenger fare mechanics.",
        "desc_en": "Taxi roof beacon indicator and passenger fare mechanics."
    },
    "cabbie": {
        "label": "cabbie",
        "label_en": "cabbie",
        "desc": "Classic taxi roof beacon indicator and passenger fare mechanics.",
        "desc_en": "Classic taxi roof beacon indicator and passenger fare mechanics."
    },
    "securica": {
        "label": "securica",
        "label_en": "securica",
        "desc": "Bulletproof and collision-resistant armored hull.",
        "desc_en": "Bulletproof and collision-resistant armored hull."
    },
    "ambulan": {
        "label": "ambulan",
        "label_en": "ambulan",
        "desc": "Emergency siren, medical beacon, and paramedic mission mechanics.",
        "desc_en": "Emergency siren, medical beacon, and paramedic mission mechanics."
    },
}

# GTA:SA Native Vehicles with Hardcoded Special Features
NATIVE_SPECIAL_FEATURES = {
    "zr350": {
        "target": "zr350",
        "label_zh": "zr350",
        "label_en": "zr350",
        "desc_zh": "Native pop-up headlights that raise automatically when lights turn on.",
        "desc_en": "Native pop-up headlights that raise automatically when lights turn on.",
        "icon": "🏎️"
    },
    "sandking": {
        "target": "sandking",
        "label_zh": "sandking",
        "label_en": "sandking",
        "desc_zh": "Native high-clearance off-road suspension with long-travel shock absorption.",
        "desc_en": "Native high-clearance off-road suspension with long-travel shock absorption.",
        "icon": "🚜"
    },
    "hydra": {
        "target": "hydra",
        "label_zh": "hydra",
        "label_en": "hydra",
        "desc_zh": "Native vector thrust nozzles supporting vertical takeoff and landing.",
        "desc_en": "Native vector thrust nozzles supporting vertical takeoff and landing.",
        "icon": "✈️"
    },
    "copcarla": {
        "target": "copcarla",
        "label_zh": "copcarla",
        "label_en": "copcarla",
        "desc_zh": "Native emergency lightbar and siren.",
        "desc_en": "Native dual-color emergency lightbar and siren.",
        "icon": "🚨"
    },
    "copcarsf": {
        "target": "copcarsf",
        "label_zh": "copcarsf",
        "label_en": "copcarsf",
        "desc_zh": "Native emergency lightbar and siren.",
        "desc_en": "Native SFPD emergency lightbar and siren.",
        "icon": "🚨"
    },
    "copcarvg": {
        "target": "copcarvg",
        "label_zh": "copcarvg",
        "label_en": "copcarvg",
        "desc_zh": "Native emergency lightbar and siren.",
        "desc_en": "Native LVPD emergency lightbar and siren.",
        "icon": "🚨"
    },
    "fbiranch": {
        "target": "fbiranch",
        "label_zh": "fbiranch",
        "label_en": "fbiranch",
        "desc_zh": "Native covert dashboard strobe and siren.",
        "desc_en": "Native covert dashboard strobe and siren.",
        "icon": "🕵️"
    },
    "taxi": {
        "target": "taxi",
        "label_zh": "taxi",
        "label_en": "taxi",
        "desc_zh": "Native roof light and passenger taxi fares.",
        "desc_en": "Native roof light and passenger taxi fares.",
        "icon": "🚖"
    },
    "cabbie": {
        "target": "cabbie",
        "label_zh": "cabbie",
        "label_en": "cabbie",
        "desc_zh": "Native vintage taxi roof light and fares.",
        "desc_en": "Native vintage taxi roof light and fares.",
        "icon": "🚖"
    }
}

# Standard GTA SA Carcols Palette (128 Colors RGB)
CARCOLS_PALETTE = {
    0: "#000000", 1: "#f5f5f5", 2: "#2a77a1", 3: "#840410", 4: "#263739", 5: "#86446e",
    6: "#d78e10", 7: "#4c75b7", 8: "#b8b8b8", 9: "#c5c5c5", 10: "#384752", 11: "#475d69",
    12: "#4a5960", 13: "#66757b", 14: "#9bafb6", 15: "#272a2b", 16: "#6e1818", 17: "#731c1c",
    18: "#832424", 19: "#972c2c", 20: "#aa3838", 21: "#ba4848", 22: "#202830", 23: "#2b3b49",
    24: "#3a5168", 25: "#496887", 26: "#577fa6", 27: "#6594c4", 28: "#1e2c1e", 29: "#293d29",
    30: "#365136", 31: "#426742", 32: "#517f51", 33: "#5e975e", 34: "#30261e", 35: "#423429",
    36: "#564436", 37: "#6c5644", 38: "#856b54", 39: "#9e7f64", 40: "#3c2a1a", 41: "#513923",
    42: "#6a4a2e", 43: "#855d3a", 44: "#a37247", 45: "#c08754", 46: "#331a26", 47: "#472435",
    48: "#5d3046", 49: "#753c58", 50: "#8e496a", 51: "#a7567d", 52: "#2e2e1f", 53: "#40402b",
    54: "#545439", 55: "#6b6b49", 56: "#828259", 57: "#9a9a69", 58: "#1c2e2e", 59: "#274040",
    60: "#345454", 61: "#426b6b", 62: "#508282", 63: "#5e9a9a", 64: "#2e1c2e", 65: "#402740",
    66: "#543454", 67: "#6b426b", 68: "#825082", 69: "#9a5e9a", 70: "#1a1a1a", 71: "#262626",
    72: "#333333", 73: "#404040", 74: "#4d4d4d", 75: "#5a5a5a", 76: "#666666", 77: "#737373",
    78: "#808080", 79: "#8c8c8c", 80: "#999999", 81: "#a6a6a6", 82: "#b3b3b3", 83: "#bfbfbf",
    84: "#cccccc", 85: "#d9d9d9", 86: "#e6e6e6", 87: "#f2f2f2", 88: "#ffffff", 89: "#d01010",
    90: "#10d010", 91: "#1010d0", 92: "#d0d010", 93: "#10d0d0", 94: "#d010d0", 95: "#ff6600",
    96: "#ffcc00", 97: "#99ff00", 98: "#00ff66", 99: "#00ffcc", 100: "#0099ff", 101: "#6600ff",
    102: "#cc00ff", 103: "#ff0099", 104: "#663300", 105: "#996633", 106: "#cc9966", 107: "#ffcc99",
    108: "#336600", 109: "#669933", 110: "#99cc66", 111: "#ccff99", 112: "#003366", 113: "#336699",
    114: "#6699cc", 115: "#99ccff", 116: "#330066", 117: "#663399", 118: "#9966cc", 119: "#cc99ff",
    120: "#660033", 121: "#993366", 122: "#cc6699", 123: "#ff99cc", 124: "#333300", 125: "#666633",
    126: "#999966", 127: "#cccc99"
}

from .vanilla_audio_data import VANILLA_AUDIO_SETTINGS
